main:
  - name: Home
    url: '/'
    weight: 10
  - name: About
    url: '/about'
    weight: 20
  - name: Experience
    url: '/experience'
    weight: 30
  - name: Projects
    url: '/projects'
    weight: 40
  - name: Contact
    url: '/contact'
    weight: 50