main:
  - name: Home
    url: /
    weight: 1
  - name: About
    url: about
    weight: 10
  - name: Intro
    url: /author/이진규/
    weight: 20
  - name: Study
    url: studies
    weight: 30
  - name: study
    parent: Study
    url: study
    weight: 31
  - name: Events
    parent: Study
    url: event
    weight: 32
  - name: Projects
    url: projects
    weight: 40
  - name: itproject
    parent: Projects
    url: itproject
    weight: 41
  - name: webproject
    parent: Projects
    url: webproject
    weight: 42
  - name: Contact
    url: cont
    weight: 50
  - name: Contact1
    parent: Contact
    url: contact
    weight: 51
  - name: Contact2
    parent: Contact
    url: contact2
    weight: 52  