main:
  - name: Home
    url: '/'
    weight: 10
  - name: About
    url: '/about'
    weight: 20
  - name: Posts
    url: '/post'
    weight: 30
  - name: Projects
    url: '/project'
    weight: 40
  - name: Contact
    url: '/contact'
    weight: 50