main:
  - name: Home
    url: '/'
    weight: 10
  - name: About
    url: '/about/'
    weight: 20
  - name: Experience
    url: '/experience/'
    weight: 30
  - name: Projects
    url: '/projects/'
    weight: 40
  - name: Contact
    url: '/contact/'
    weight: 50
  - name: test
    url: '#'
    weight: 50
    identifier: ttt
  - name: test1
    url: '/test/test1/'
    weight: 1
    parent: ttt
  - name: test2
    url: '/test/test2/'
    weight: 2
    parent: ttt