# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo link in bio theme powered by Wowchemy website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site logo
navbar:
  logo:
    enable: true
    text: "my logo"  # 로고 대신 텍스트 사용
  menu_alignment: center  # 이 옵션이 있다면, 메뉴 항목들을 중앙 정렬
  menu_padding: 40px  # 메뉴 항목 사이의 패딩을 늘려 중앙으로 밀어냄

# Site footer
footer:
  copyright:
    notice: '© {year} Me'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
