# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo link in bio theme powered by Wowchemy website builder.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: c
    show_logo: true
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: true

logo:
  # 이 부분을 추가하거나 수정하세요
  image: "media/logo.svg"
  image_light: "media/logo.svg"
  image_dark: "media/logo.svg"
  enable: true

# Site footer
footer:
  copyright:
    notice: '© {year} Me'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
